### ISSUE TITLE
inverse option for block Transformer

### ISSUE THREAD

**Issue by agamemnonc** [axopy/axopy#61]
There are cases that a `sklearn` `Transformer` needs to be used for inverse transforms (e.g. classifier returns prediction in label encoded format, but we want to use the original encoding, such as categorical value. )

I suggest including an `inverse` input argument in block `Transformer` to support this feature. 

Happy to submit a PR.

**Comment by ixjlyons** [comment]
Yep, I totally overlooked this. An `inverse` kwarg sounds good to me.
