### ISSUE TITLE
Drop Python 2 and 3.4?

### ISSUE THREAD

**Issue by ixjlyons** [axopy/axopy#67]

**Comment by agamemnonc** [comment]
+1
I, for one, definitely wouldn't mind.
sklearn  has recently also dropped support for < 3.5.

**Comment by ixjlyons** [comment]
Great. Yeah I think pretty much all the dependencies are queued up to drop Python 2 this year. It would be great to get rid of the conda stuff on Travis which takes about twice as long (granted, it has to install miniconda), and I've always been very annoyed by the caveat about PyQt5 for Python < 3.5.

Maybe I'll just make another release soon then drop it from there. I suspect this will affect no one (though if someone is lurking and really needs Python 2 or 3.4, speak now! :)
